### ISSUE TITLE
想法挺好

### ISSUE THREAD

**Issue by xuexb** [nimojs/learn-js#1]
持续关注,对了,你的`tab.js`呢...

ps: 正在换工作,稳定后会向你多学习.

**Comment by nimoc** [comment]
:smiley:  感谢支持，这项目是为了提高公司同事的组件开发和 JS 实战经验。适合某个组件开发经验少的人按阶段的逐步实现。我要开发 `tab.js` 就在 GitHub 单独开发创建个项目了。

我们平时开发是使用支付宝开发的 [switchable](http://spmjs.io/docs/arale-switchable/latest/) 。

**Comment by xuexb** [comment]
@nimojs 可以往里放别的组件么,比如写的美化单选,复选啥的

**Comment by nimoc** [comment]
可以的，欢迎发 PR 过来。遵循循序渐进的原则就可以了。

先实现
然后封装成一个函数
然后提供API
然后丰富API

**Comment by xuexb** [comment]
@nimojs  
1. 为啥是`gh-pages`分支呢...
2. 我感觉提供一个在线预览的地址会更好...

**Comment by nimoc** [comment]
gh-pages 是为了在线预览

http://nimojs.github.io/learn-js/package/tab/code/xuexb/1/index.html

**Comment by xuexb** [comment]
好吧,我out了,忘了这回事

**Comment by 2319103827** [comment]
> nimojs
> 请问下怎么生成在线预览的地址呢

**Comment by nimoc** [comment]
在 github 上创建 gh-pages 分支

然后通过这样的方式访问 

http://nimojs.github.io/learn-js/README.md

branch: gh-pages
