### ISSUE TITLE
还有其他例子会持续发布嘛

### ISSUE THREAD

**Issue by fromIRIS** [nimojs/learn-js#15]

**Comment by nimoc** [comment]
感谢关注，最近在忙其他事，后续会循序渐进的提供更高级的组件开发挑战。

**Comment by xuexb** [comment]
要不要再来个`ajax`异步分页 [:p]

**Comment by nimoc** [comment]
@xuexb 
恩，这个好。可以延伸出很多实战应用。

**Comment by nimoc** [comment]
但是 AJAX分页中页码的**页码生成**是值得做成一个组件的，否则计算出分页比较麻烦。

https://github.com/nimojs/paging

而做出页码控件后分页就变得非常简单了[AJAX无刷新分页](http://docs.spmjs.io/paging/latest/examples/ajax.html)

---

其他AJAX的使用场景比如：
AJAX表单提交，这个的核心是表单验证组件。

**Comment by hifizz** [comment]
可以来个轮播图啊，这个可以衍生好多东西。而且完全可以参照bootstrap中的组件来做一个系列组件开发挑战啊！从最简单的开始，逐步完善一个完整的组件，再到完成一个系列组件，我觉得这个效果会好。

**Comment by hifizz** [comment]
还是希望这个项目能有一定的连贯性，跳跃不要太大。最好是后面做的东西能够用到前面学的。

**Comment by nimoc** [comment]
@haungdongshan1  你指的是完成一个组件生态的开发？

欢迎按照现在的组件开发需求格式像本项目发送组件挑战 [Pull requests](https://github.com/nimojs/learn-js/pulls)
