### ISSUE TITLE
github离线安装包使用方法

### ISSUE THREAD

**Issue by nimoc** [nimojs/learn-js#2]
相关阅读： [克隆与请求合并](https://github.com/nimojs/learn-js/blob/gh-pages/fork%26pullrequests.md)

**Comment by inwikipedia** [comment]
github客户端git账号一直登录失败,网页登录正常

**Comment by langrren** [comment]
github离线安装包http://pan.baidu.com/s/1Hkewm 引用自知乎用户@姚泽源 的答案
