### ISSUE TITLE
如何利用json测试接口？

### ISSUE THREAD

**Issue by dontry** [nimojs/learn-js#32]
新手。
看到题目有提供json格式的数据类型，如何利用他们进行测试？
dialog({
    trigger: '#btn',
    content: '<strong>哈哈</strong>',
    onClose: function (element) {
        /*
        element 弹出层 DOM 元素
        */
    }
})

**Comment by nimoc** [comment]
问题定向到 https://github.com/nimojs/learn-js/issues/33
